name: "Build bom and licenses"
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 3 * * *
permissions: read-all
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
      - run: |
          echo $(go env GOPATH)/bin >> $GITHUB_PATH
          go install sigs.k8s.io/bom/cmd/bom@v0.5.1
      - run: |
          bom generate -n https://kuma.io  -o sbom.json  --format json .
          jq '.packages[] | with_entries(select([.key] | inside(["name", "versionInfo", "licenseConcluded"])))' sbom.json > licenses.json
      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: sbom
          path: |
            sbom.json
            licenses.json
