name: CI

on:
  push:
    branches: ["koyeb-release"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GOOS: linux
  COREDNS_GIT_REPOSITORY: https://github.com/coredns/coredns.git
  KUMACTL_INSTALL_USE_LOCAL_IMAGES: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Seed env
        run: |
          echo $GITHUB_SHA | awk '{ printf "BUILD_INFO_VERSION=koyeb-%.7s\n", $1 }' >> $GITHUB_ENV
          echo "DOCKER_REGISTRY=eu.gcr.io/$PROJECT_ID" >> $GITHUB_ENV
      - name: Configure gcloud
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json --project $PROJECT_ID
          gcloud auth configure-docker
      - name: Build and push to docker
        run: |
          make build/coredns
          for i in kuma-cp kuma-dp kumactl; do
            make build/${i}
            make docker/build/${i}
            docker tag $DOCKER_REGISTRY/${i}:$BUILD_INFO_VERSION $DOCKER_REGISTRY/${i}:latest
            docker push $DOCKER_REGISTRY/${i}:$BUILD_INFO_VERSION
            docker push $DOCKER_REGISTRY/${i}:latest
          done
