name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  pr_comments:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          make dev/tools
          git checkout go.mod go.sum
      - name: format
        if: contains(github.event.comment.body, '/format')   # check the comment if it contains the keywords
        run: |
          make format
      - name: run golden_files
        if: contains(github.event.comment.body, '/golden_files')  # check the comment if it contains the keywords
        run: |
          make test UPDATE_GOLDEN_FILES=true
      - name: commit and push fixes
        run: |
          if [[ ! `git diff --exit-code --stat` ]]; then
            git commit -s -m "fix(ci): format files"
            git push
          fi
